### ISSUE TITLE
this should probably go in github

### ISSUE THREAD

**Issue by izzymiller** [izzymiller/rock_climbing_data#1]
Link to JIRA issue: https://izzzzy.atlassian.net/browse/TES-1

**Comment by izzymiller** [comment]
Let's pretend this is being worked on now! @izzymiller

**Comment by izzymiller** [comment]
@izzymiller

**Comment by rachelmjohnson** [comment]
@izzymiller funsies!

**Comment by izzymiller** [comment]
testing to py

**Comment by izzymiller** [comment]
blah blah - synced from jira

**Comment by izzymiller** [comment]
Closed from JIRA
